### ISSUE TITLE
Closed Week 7. Task: Consistency

### ISSUE THREAD

**Issue by oneway1222** [LiamBoylan/Chirp-Whiz#14]
Test that the random generated questions are not in error (important).

**Comment by znoor000** [comment]
Assured that no bird repeats twice consecutively in any quiz. Accomplished by Liam in quiz.js during week 7

**Comment by LiamBoylan** [comment]
Birds shouldn't appear twice in a row in the quiz. This makes for redundant questions and pulls the user out of the experience.
