### ISSUE TITLE
Closed Week 7. Task: eBird API

### ISSUE THREAD

**Issue by LiamBoylan** [LiamBoylan/Chirp-Whiz#2]
Figure out how to use the eBird API to acquire images and audio samples of different bird species.

**Comment by znoor000** [comment]
currently in progress by Luis and Hangil

**Comment by znoor000** [comment]
eBird api does not give any image or audio resources. Must use images from https://www.allaboutbirds.org/ and audio from https://www.mbr-pwrc.usgs.gov/id/htmwav/ then credit them in the about page

**Comment by znoor000** [comment]
sources utilized (iin birdlist.js) and credited (in about.js) as of week 7 by Zohora
