### ISSUE TITLE
Glossary page navbar glitch

### ISSUE THREAD

**Issue by LiamBoylan** [LiamBoylan/Chirp-Whiz#46]
When you enter a certain bird's page on the glossary page, using the navbar to travel to another page (such as Home, Quiz, Bird Form) instead sends you back to the glossary page. Using the navbar should instead link you to page that you're trying to travel to. This is probably a clash between using both React-Bootstrap for the navbar and react routing for the various bird pages in the glossary, as using the navbar in a bird's glossary page appends the desired page at the end of /glossary/ in the url.

**Comment by znoor000** [comment]
Solved by Liam during week 8
