### ISSUE TITLE
Task: Glossary

### ISSUE THREAD

**Issue by znoor000** [LiamBoylan/Chirp-Whiz#47]
implement a glossary which has a list of all the birds on the app. when any bird is clicked on (like a button), the bird's profile page will open and show all info on the bird

**Comment by znoor000** [comment]
Hangill implemented Glossary.js on week 4. Liam added buttons that opened bird profile pages (and implemented bird profile pages with all bird info) on week 5.

**Comment by oneway1222** [comment]
Using the database we have on AWS Dynamodb, listed the bird species.
