### ISSUE TITLE
Task: User Story Wikis

### ISSUE THREAD

**Issue by znoor000** [LiamBoylan/Chirp-Whiz#52]
Luis, Hangill, Zohora, and Liam must make user stories for this project and upload them on the wiki. each member must have at least 10 each.

**Comment by znoor000** [comment]
Task completed by everyone on week 1

**Comment by LiamBoylan** [comment]
The user stories are what our users would actually want from the app and why they want those features. Helps guide the development of our app and the creation of our todos and tasks.
