### ISSUE TITLE
Task: Background Habitat Image

### ISSUE THREAD

**Issue by znoor000** [LiamBoylan/Chirp-Whiz#57]
Implement background images of habitats of the birds throughout the app. for questions, specifically show the habitat of the target bird.

**Comment by znoor000** [comment]
implemented by Liam on week 4

**Comment by znoor000** [comment]
removed implementation from entire app. Professor Grossberg advised that it was too much (too disorganized to the central theme).

**Comment by znoor000** [comment]
Will not re-implement

**Comment by LiamBoylan** [comment]
Could be implemented, but not in the way we originally tried. Too cluttered
