### ISSUE TITLE
Task: Bootstrap

### ISSUE THREAD

**Issue by znoor000** [LiamBoylan/Chirp-Whiz#58]
Implement all buttons, image containers, and other containers necessary for the layout of the pages of Chirp Whiz using Bootstrap. Professor Grossberg advised that bootstrap would unify the look of the app.

**Comment by znoor000** [comment]
Liam changed styling to bootstrap components on week 5
(also added navigation bar via bootstrap)

**Comment by znoor000** [comment]
note that following week 5, everyone started using bootstrap components. Liam migrated all styling to bootstrap for changes *up to* week 5.

**Comment by LiamBoylan** [comment]
I changed our original components to use Bootstrap, it makes the processes much easier and more efficient.
