### ISSUE TITLE
Task: Question Layout

### ISSUE THREAD

**Issue by LiamBoylan** [LiamBoylan/Chirp-Whiz#6]
Implement a visually appealing and easy to use layout for the multiple choice questions.

**Comment by znoor000** [comment]
covered in the low fi wireframes wiki page. it is a work in progress but has accomplished the general idea. https://github.com/LiamBoylan/Chirp-Whiz/wiki/Low-fi-wireframes

**Comment by znoor000** [comment]
question page was laid out by Luis - back-end and front-end (week 3), styled by Zohora (week 6), progress bar added by Hangill (week 6)
