### ISSUE TITLE
Task: Progress Bar

### ISSUE THREAD

**Issue by znoor000** [LiamBoylan/Chirp-Whiz#61]
Add a quiz progress bar at the top of quiz question pages so that the user can see how far along they are

**Comment by znoor000** [comment]
Hangill implemented the progress bar in QuizQuestion.js on week 6

**Comment by oneway1222** [comment]
We can choose the number of questions (5, 10 or 20 questions). Depending on the number of the question, the progress bar shows how much the user solved the questions.
