### ISSUE TITLE
Task: Fix Fit of Bird Profiles 

### ISSUE THREAD

**Issue by znoor000** [LiamBoylan/Chirp-Whiz#63]
Fix the styling of bird profiles in Glossary so that the user does not have to scroll to see all information.

**Comment by znoor000** [comment]
Liam completed this task during week 6. Bird image was resized and pushed to the left of the page while bird audio and textual info were moved to the right side of the page. Implemented in Glossary.js.

**Comment by LiamBoylan** [comment]
Changed how the glossary pages looked to make the pages more dynamic and easier to peruse.
