### ISSUE TITLE
Closed Week 5. Task: Host Website

### ISSUE THREAD

**Issue by znoor000** [LiamBoylan/Chirp-Whiz#65]
Host Chirp Whiz using AWS

**Comment by znoor000** [comment]
Liam hosted the site on S3 server on Amplify:
http://chirp-whiz-20191115172533-hostingbucket-myenv.s3-website.us-east-2.amazonaws.com/home
during week 5

**Comment by LiamBoylan** [comment]
Hosted the site on S3 server on Amplify:
http://chirp-whiz-20191115172533-hostingbucket-myenv.s3-website.us-east-2.amazonaws.com/home
during week 5
