### ISSUE TITLE
Week 5 Task: Glossary Bird Profiles

### ISSUE THREAD

**Issue by znoor000** [LiamBoylan/Chirp-Whiz#66]
Update glossary so that it lists buttons with bird image and names. when any bird is clicked on, the bird's profile page will open and show all info on the bird.

**Comment by znoor000** [comment]
In Glossary.js, Liam added buttons that opened bird profile pages (and implemented bird profile pages with all bird info) on week 5.

**Comment by LiamBoylan** [comment]
Used React-Bootstrap to style the glossary and add bird profiles using cards.
