### ISSUE TITLE
Closed Week 5. Task: Add Buttons to Home

### ISSUE THREAD

**Issue by znoor000** [LiamBoylan/Chirp-Whiz#68]
Add Quiz, Glossary, and Bird Form buttons to the main home page so it doesn't look empty

**Comment by znoor000** [comment]
Implemented in Home.js by Liam during week 5.

**Comment by LiamBoylan** [comment]
Made home page buttons more user friendly and linked to tutorial, quiz, glossary, and user profile pages. The tutorial button is more prominent for new players.
