### ISSUE TITLE
Closed Week 5. Task: Unit Testing

### ISSUE THREAD

**Issue by znoor000** [LiamBoylan/Chirp-Whiz#69]
Start implementing tests for functions.

**Comment by znoor000** [comment]
Everyone implemented 33 Unit Tests for form inputs, quiz logic, data retrieval, and mocking auxiliary functions during week 5

**Comment by LiamBoylan** [comment]
Jest unit tests for the home page, leaderboard, quiz, tutorial, and user pages.
