### ISSUE TITLE
Closed Week 8. Task: Glossary Search

### ISSUE THREAD

**Issue by Glider717** [LiamBoylan/Chirp-Whiz#7]
Implement a glossary system that allows users to look up pictures of birds and their corresponding bird calls by entering the bird name in a search bar.

**Comment by znoor000** [comment]
Implemented during week 8 by Liam

**Comment by LiamBoylan** [comment]
Search feature added at the end. Users can now type in the search bar and only birds with that text in their name will appear on the page.

**Comment by oneway1222** [comment]
The final updated result of #47
