### ISSUE TITLE
Closed Week 5. Task: Integration Testing

### ISSUE THREAD

**Issue by znoor000** [LiamBoylan/Chirp-Whiz#70]
Start implementing tests for components of the web-app

**Comment by znoor000** [comment]
Everyone implemented 9 Integration Tests that covered page changes on button click and 5 snapshots during week 5. React Testing Library was utilized.

**Comment by LiamBoylan** [comment]
We used integration testing for pretty much every component. Most components have snapshots along with tests for other functionality such as rendering specific information when fed specific properties.
