### ISSUE TITLE
Task: User 

### ISSUE THREAD

**Issue by znoor000** [LiamBoylan/Chirp-Whiz#78]
Add a user page that shows the user's username, email, and other characteristics.

**Comment by znoor000** [comment]
add in some score-keeping

**Comment by znoor000** [comment]
Accomplished by Hangill during Week 7 in UserPage.js

**Comment by oneway1222** [comment]
On week 7, it shows the username, email, and a table of all the birds on the app. The table shows how many times the user identified the birds correctly or incorrectly, and the accuracy in identifying those birds.

**Comment by oneway1222** [comment]
Added the feature that shows how many questions users solved in total, how many questions solved correctly or incorrectly, and the accuracy also during week 8.
