### ISSUE TITLE
Task: Quiz Selection Type

### ISSUE THREAD

**Issue by Glider717** [LiamBoylan/Chirp-Whiz#8]
Allow the user to pick and choose which topic to be quizzed on. (Bird calls only, bird shapes, birds by location, etc.)

**Comment by znoor000** [comment]
on quiz start page user can choose whether questions will include audio, image, or both. they can choose a session of 5, 10, or 20 questions. They can also choose to be quized on birds from a range of habitats. Implemented by Luis on week 6 in Quiz.js
