### ISSUE TITLE
Leaderboard sorting issue

### ISSUE THREAD

**Issue by LiamBoylan** [LiamBoylan/Chirp-Whiz#86]
The leaderboard should sort the users by accuracy, however some times it's out of order. New users are placed at the top above the 100% and sometimes lower scores are placed above higher scores. The issue could be that the leaderboard sorts by the first digit of the accuracy score, and maybe another factor of the user data is affecting the sorting.

**Comment by znoor000** [comment]
Liam fixed this issue during week 8

**Comment by LiamBoylan** [comment]
The sorting for the leaderboard sorted by the first digit, so it put 100% below 20%. It was also in reverse so 100% was at the top but 20% was above 50%. I reversed it back then changed the sorting to sort by the entire accuracy score.
